'use client';

import { FormEvent, useState } from 'react';
import { ExternalLink, Headphones, Music2, Play, Search, Sparkles } from 'lucide-react';

type Track = { id:string; name:string; artists:string; image:string; youtubeUrl:string };

export default function Home(){
 const [query,setQuery]=useState(''); const [tracks,setTracks]=useState<Track[]>([]); const [selected,setSelected]=useState<Track|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function searchMusic(e:FormEvent){ e.preventDefault(); if(!query.trim())return; setLoading(true);setError(''); try{const r=await fetch(`/api/search?q=${encodeURIComponent(query.trim())}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Search failed');setTracks(d.tracks||[]);setSelected(d.tracks?.[0]||null)}catch(err){setError(err instanceof Error?err.message:'Search failed');setTracks([]);setSelected(null)}finally{setLoading(false)}}
 return <main><div className="orb orbOne"/><div className="orb orbTwo"/><nav className="nav shell"><div className="brand"><div className="brandMark"><Music2 size={20}/></div><span>Music Listener</span></div><div className="spotifyBadge">YouTube Music</div></nav>
 <section className="hero shell"><div className="eyebrow"><Sparkles size={15}/> Your music, one search away</div><h1>Find the song.<br/><span>Feel the moment.</span></h1><p>Search for music and play it right here without leaving Music Listener.</p><form className="searchBox" onSubmit={searchMusic}><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a song or artist..." aria-label="Search music"/><button disabled={loading}>{loading?'Searching…':'Search'}</button></form>{error&&<div className="notice"><Headphones size={18}/>{error}</div>}</section>
 <section className="content shell">{tracks.length===0&&!loading?<div className="emptyState"><div className="vinyl"><Music2 size={38}/></div><h2>What do you want to hear?</h2><p>Search for Burna Boy, Adele, Drake, Azawi, or any song you love.</p></div>:<div className="grid"><div><div className="sectionHeading"><h2>Search results</h2><span>{tracks.length} videos</span></div><div className="trackList">{tracks.map((t,i)=><button key={t.id} className={`trackRow ${selected?.id===t.id?'active':''}`} onClick={()=>setSelected(t)}><span className="index">{selected?.id===t.id?<Play size={15} fill="currentColor"/>:i+1}</span><img src={t.image} alt=""/><span className="trackText"><strong>{t.name}</strong><small>{t.artists}</small></span><span className="album">YouTube</span></button>)}</div></div><aside className="playerCard">{selected&&<><div className="nowPlayingLabel">NOW PLAYING</div><img className="cover" src={selected.image} alt=""/><h3>{selected.name}</h3><p>{selected.artists}</p><iframe title={`Player for ${selected.name}`} src={`https://www.youtube.com/embed/${selected.id}?autoplay=1&playsinline=1`} width="100%" height="240" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/><a href={selected.youtubeUrl} target="_blank" rel="noreferrer">Open on YouTube <ExternalLink size={14}/></a></>}</aside></div>}</section><footer className="shell">Music and video are streamed from YouTube. Music Listener does not download or redistribute media.</footer></main>
}
